import Link from "next/link";
import "../styles/globals.css";
import { GlobalNav } from "@/components/GlobalNav";
import { NavHeader } from "@/components/NavHeader";
import { Footer } from "@/components/Footer";
import { PageHeader } from "@/components/PageHeader";
import { IBM_Plex_Mono } from "next/font/google";

export const metadata = {
  title: "Prīmaevus",
  description: "Generated by Next.js",
};

const ibm = IBM_Plex_Mono({
  variable: "--font-plex",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${ibm.variable}`}>
      <head />
      <body
        className="font-mono overflow-y-scroll"
        style={{ WebkitFontSmoothing: "none" }}
      >
        <div className="flex md:flex-col w-auto md:fixed z-10 border-stone-200 border-2">
          <NavHeader />
          <GlobalNav />
        </div>
        <div className="md:pl-48">
          <div className="flex flex-col min-h-screen justify-between">
            <div className="">{children}</div>
            <div className="">
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
